# tomcat
server:
  port: 8080
spring:
  #redis??
  redis:
    #????
    sentinel:
      master: mymaster
      nodes: 192.168.92.129:16391,192.168.92.129:16392,192.168.92.129:16393
    #????
    password: 123456 #redis????(????requirepass??)
    database: 0 #?????
    connect-timeout: 3000 #??????
    #?????(lettuce??)
    lettuce:
      pool:
        max-active: 8 #?????
        max-idle: 8 #??????
        min-idle: 8 #??????
        max-wait: -1 #??????(-1 ?????)